#!/bin/bash
# Setup symlink that connects to MEGAN env
# Similar to link_qiime2

cd ${HOME}
export envPath=/gpfs/group/dml129/default/microbiome_workshop2020/sw/megan
export symlinkPath=${HOME}/megan

if [[ -d ${envPath} && ! -L ${symlinkPath} ]]; then
    ln -s ${envPath} ${symlinkPath}
    echo -e "\nUse the following commands to activate the megan environment"
    echo "$ module load python/3.6.3-anaconda5.0.1"
    echo "$ cd ~"
    echo -e "$ source activate megan\n"

elif [ -L ${symlinkPath} ]; then
    echo -e "\nThe symlink has already been setup"
    echo "Use the following commands to activate the megan environment"
    echo "$ module load python/3.6.3-anaconda5.0.1"
    echo "$ cd ~"
    echo -e "$ source activate megan\n"

elif [ ! -d ${envPath} ]; then
    echo ${envPath} "does not exist"

else
    echo "Something went wrong, please contact i-ASK center"
fi
